name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:  # Первый блок (как на твоем скрине)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/expressv2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: publish-docker-hub
    steps:
      - name: Simple Deploy Simulation
        run: |
          echo "Connecting to server..."
          echo "Updating docker containers..."
          echo "Deploy successful!"